export const API_ERROR_CODE = {
  ORDER_NOT_FOUND_OR_TOO_LATE: 20001,
  POSITION_STATUS_NOT_NORMAL: 30013,
  CANNOT_SET_TRADING_STOP_FOR_ZERO_POS: 30024,
  /** Seen when placing an order */
  INSUFFICIENT_BALANCE_FOR_ORDER_COST: 30031,
  POSITION_IDX_NOT_MATCH_POSITION_MODE: 30041,
  /** Seen if a conditional order is too large */
  INSUFFICIENT_BALANCE: 30042,
  /** E.g. trying to change position margin while on cross */
  POSITION_IS_CROSS_MARGIN: 30056,
  POSITION_MODE_NOT_MODIFIED: 30083,
  ISOLATED_NOT_MODIFIED: 30084,
  RISK_LIMIT_NOT_EXISTS: 30090,
  LEVERAGE_NOT_MODIFIED: 34036,
  SAME_SLTP_MODE: 37002,
} as const;
